{% set build_number = 8 %}

package:
  name: _openmp_mutex
  version: {{ version }}

build:
  number: {{ build_number }}
  string: {{ build_number }}_{{ openmp_mutex_impl }}

test:
  commands:
    - echo "{{ openmp_mutex_impl }} mutex selected"

about:
  summary: Mutex metapackage for selecting a single OpenMP runtime family
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/AnacondaRecipes/_openmp_mutex-feedstock

extra:
  recipe-maintainers:
    - ELundby45